### ISSUE TITLE
Chunks appear out of order

### ISSUE THREAD

**Issue by rdmcgregor** [chen-ye/hubot-chunkify#3]
Chunks appear out of sequence, and apparently in random order.

This is witnessed when used with `hubot-fb` adapter.  Not tested with any other adapter.

Example is when a hubot responds with the laws of robotics, they display out of sequence.

**Comment by TobiTenno** [comment]
I think the problem is that it also chunks messages per-line with that, too. I proposed a fix for some of it in #2, but I don't know if it fixes the out-of-order issues. the problem for that is that, since coffee and javascript are async, and depending on how your adapter sends messages, it could cause different messages to send "faster".

**Comment by chen-ye** [comment]
fixed in https://github.com/chen-ye/hubot-fb/pull/12 for `hubot-fb`

**Comment by TobiTenno** [comment]
hmmm, did it get committed here too?

**Comment by chen-ye** [comment]
The problem was on the adapter side. No changes should be required for `hubot-chunkify`.   (of course, you'll need to use an adapter that supports ordered message sending, but it's better to implement that on the adapter than in chunkify)
